name: iremember
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.0
  flutter_bloc: ^3.1.0
  image_picker: ^0.6.3+4
  cached_network_image: ^2.0.0
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  permission_handler: ^4.2.0+hotfix.3
  firebase_storage: ^3.1.1
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
